### PR TITLE
Feature/integrate audio base wav

### PR DESCRIPTION
**Pull request by h4yn0nnym0u5e**
First go at removing WaveMover and integrating its functionality into AudioBaseWav. Appears to be working OK, same performance with test sineNN0.wav files and no memory leaks apparent with dynamic construction and destruction of AudioPlayWav objects.

No idea why github is saying there are conflicts...

### CODE REVIEW

**Comment by FrankBoesing** [comment]
Hi Jonathan,
thx!!
Easiest is to delete your repository and do a new fork.

I resolved the conflict - it was a comment only..

Frank

**Comment by h4yn0nnym0u5e** [comment]
Doesn't that then lose all my development history? I've often found I need to go back to see when or why I made a change... If I did a PR from my main to yours, because mine is now 15 commits ahead (?!), it would change no files. And I suspect we'd stay in step for just as long as it took to get to the next PR. Git is nuts...

Glad it was just a comment.

**Comment by FrankBoesing** [comment]
Hm. You could try to "rebase" too.  
Yes, sometimes, Github is...

Do you know Github Desktop? You can install it to your PC - makes many things much easier.

**Comment by FrankBoesing** [comment]
\+ you can just copy the whole repo locally, so you don't loose old versions (ehm... i think.... in theory - never tried!) ;)

**Pull request merged**
